export const TASK_NAME_MAX_LENGTH = 30;
export const DESCRIPTION_MAX_LENGTH = 200;
export const USER_NAME_MAX_LENGTH = 14;
export const PROFILE_PICTURE_MAX_LENGTH = 255;
export const CATEGORY_NAME_MAX_LENGTH = 20;
export const MAX_CATEGORIES = 4;
