export { ColorPalette, Themes } from "./theme";
export {
  GlobalStyles,
  fadeInLeft,
  fadeIn,
  slideIn,
  slideInBottom,
  StyledLink,
  pulseAnimation,
  DialogBtn,
  PathName,
  ColorElement,
} from "./globalStyles";
export {
  GreetingHeader,
  GreetingText,
  TasksCount,
  TaskCompletionText,
  TaskCountHeader,
  TaskCountTextContainer,
  TasksCountContainer,
  ProgressPercentageContainer,
  Offline,
  StyledProgress,
} from "./home.styled";
export { Container, Input, AddTaskButton, StyledInput } from "./addTask.styled";
export {
  TaskComponent,
  EmojiContainer,
  TaskDate,
  TaskInfo,
  TaskDescription,
  TaskHeader,
  NoTasks,
  CategoriesListContainer,
  TasksContainer,
  Pinned,
  TimeLeft,
  TaskName,
  HighlightedText,
  SearchInput,
  RingAlarm,
  ShowMoreBtn,
  StyledRadio,
  SelectedTasksContainer,
} from "./tasks.styled";
